import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <div className="min-h-screen h-full w-full flex flex-col bg-brand-light overflow-hidden">
        <Head>
          <title>STKYFNGRS</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header>
          <div>
            <link href="?"></link>
          </div>
        </header>
      </div>
    </>
  )
}
