import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <div className="min-h-screen h-full w-full flex flex-col bg-brand-light overflow-hidden">
        <Head>
          <title>STKYFNGRS</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <header className="min-w-full text-gray-800 py-14 px-4 md:px-0">
          <div className="flex items-center container mx-auto max-w-5xl justify-between h-full">
            <a href="#">
              <span className="font-coiny text-xl md:text-3xl font-bold">
                STKY
              </span>
              <span className="font-coiny text-xl md:text-3xl font-bold bg-gradient-to-br from-brand-black to-brand-purple pr-2 bg-clip-text text-transparent">
                FNGRS
              </span>
            </a>
          </div>

          <></>
        </header>
      </div>
    </>
  )
}
